apiVersion: v1
kind: Service
metadata:
  name: minecraft
spec:
  type: NodePort
  ports:
  - port: 25565
    targetPort: 25565
  selector:
    app: mc-vanilla
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-direwolf20-datadir
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-direwolf20
spec:
  selector:
    matchLabels:
      app: minecraft-direwolf20
  template:
    metadata:
      labels:
        app: minecraft-direwolf20
    spec:
      containers:
      - image: itzg/minecraft-server
        name: minecraft-direwolf20
        env:
          # Use secret in real usage
        - name: EULA
          value: "true"
        - name: TYPE
          value: "CURSEFORGE"
        - name: CF_SERVER_MOD
          value: "https://www.curseforge.com/minecraft/modpacks/ftb-presents-direwolf20-1-12/download/2690320/file"
        - name: MEMORY
          value: "4G"
        ports:
        - containerPort: 25565
          name: main
        volumeMounts:
        - name: mc-data
          mountPath: /data
        resources:
          requests:
            memory: "4000Mi"
          limits:
            memory: "4000Mi"
      tolerations:
        - key: "memory"
          operator: "Equal"
          value: "high"
          effect: NoExecute
      volumes:
      - name: mc-data
        persistentVolumeClaim:
          claimName: mc-vanilla-datadir
