apiVersion: v1
kind: Service
metadata:
  name: mc-vanilla
spec:
  type: NodePort
  ports:
  - port: 25565
    targetPort: 25565
  selector:
    app: mc-vanilla
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-vanilla
spec:
  selector:
    matchLabels:
      app: mc-vanilla
  template:
    metadata:
      labels:
        app: mc-vanilla
    spec:
      containers:
      - image: itzg/minecraft-server
        name: mc-vanilla
        env:
          # Use secret in real usage
        - name: EULA
          value: "true"
        - name: TYPE
          value: "CURSEFORGE"
        - name: CF_SERVER_MOD
          value: "https://www.curseforge.com/minecraft/modpacks/all-the-mods-3/download/2721020/file"
        - name: MEMORY
          value: "4G"
        ports:
        - containerPort: 25565
          name: main
        volumeMounts:
        - name: mc-data
          mountPath: /data
        resources:
          requests:
            memory: "4000Mi"
          limits:
            memory: "4000Mi"
      tolerations:
        - key: "memory"
          operator: "Equal"
          value: "high"
          effect: NoExecute
      volumes:
      - name: mc-data
        emptyDir: {}
